apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heritage-db
  namespace: heritage
  labels:
    app.kubernetes.io/part-of: heritage-splitter
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-cinder-classic
  resources:
    requests:
      storage: 1Gi
