apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heritage-db
  labels:
    app: heritage-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heritage-documents
  labels:
    app: heritage-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
